### PR TITLE
Print a tree of the blockers of bugs

### PR DESCRIPTION
**Pull request by jml**
Now seriously suggesting for merging. 

```
FLOC-2008: flocker.node.agents.functional.test_ebs.EBSBlockDeviceAPIInterfaceTests test failure - Done (itamarst)
├── FLOC-2257: Validate the configuration supplied to storage backend plugins - Backlog
│   └── FLOC-2259: Validate ``instance_decorator`` is used to decorate classes only (not functions) - Design (wallrj)
├── FLOC-2275: flocker.acceptance.test_deployment.DeploymentTests.test_application_volume_quotas assumes datasets can be 100MB - Accepted
├── FLOC-2258: Validate the configuration supplied to storage backend plugins - Backlog
├── FLOC-2189: Support Ubuntu 15.04 with client deb packages - Done
├── FLOC-2188: Validate the configuration supplied to storage backend plugins - Backlog
│   └── FLOC-1953: flocker.node.agents.functional.test_ebs.EBSBlockDeviceAPIInterfaceTests test failure - Done (itamarst)
├── FLOC-2183: flocker/acceptance/ubuntu-14.04/aws builder should be part of expected passing set of builders for GitHub PRs - Backlog
├── FLOC-2182: Cinder acceptance tests aren't running at all - Done
├── FLOC-2179: Builder ``flocker/acceptance/aws/centos-7/aws`` should be part of known passing builders - Backlog (madhuri.yechuri)
├── FLOC-2187: flocker.node.agents.functional.test_ebs.EBSBlockDeviceAPIInterfaceTests test failure - Done (itamarst)
├── FLOC-2186: Validate the configuration supplied to storage backend plugins - Backlog
├── FLOC-2185: Cinder acceptance tests aren't running at all - Done
└── FLOC-2184: Validate the configuration supplied to storage backend plugins - Backlog
```

[Review on Reviewable](https://reviewable.io/reviews/exarkun/clusterhq_jira_tools/1)

### CODE REVIEW

**Comment by exarkun** [comment]
Got some output that doesn't look right to me:

```
(flocker-tools)jean-paul@dilaton:~/Projects/ClusterHQ/jira_tools/review$ python blockers.py 
FLOC-2008: Validate the configuration supplied to storage backend plugins - Backlog
├── FLOC-2258: flocker/client/rackspace/ubuntu-14.04 builder should be part of expected passing set of builders for GitHub PRs - Done
├── FLOC-2183: flocker/acceptance/ubuntu-14.04/aws builder should be part of expected passing set of builders for GitHub PRs - Done
├── FLOC-2182: flocker/acceptance/aws/ubuntu-14.04/loopback builder should be part of expected passing set of builders for GitHub PRs - Done
├── FLOC-2179: Builder ``flocker/acceptance/aws/centos-7/aws`` should be part of known passing builders - Done (madhuri.yechuri)
├── FLOC-2187: flocker.node.agents.functional.test_ebs.EBSBlockDeviceAPIInterfaceTests test failure - Done (itamarst)
├── FLOC-2186: Validate the configuration supplied to storage backend plugins - Backlog
├── FLOC-2185: Validate the configuration supplied to storage backend plugins - Backlog
└── FLOC-2184: Validate the configuration supplied to storage backend plugins - Backlog
```

Checking on some of these, the summaries and issue numbers don't seem to correspond at all.

**Comment by jml** [comment]
Thanks for taking a look. Some notes below to help future me (or unlikely volunteer) solve it:
- :negative_squared_cross_mark: [FLOC-2008](https://clusterhq.atlassian.net/browse/FLOC-2008) should be "Release 1.0 blockers"
- :negative_squared_cross_mark: [FLOC-2258](https://clusterhq.atlassian.net/browse/FLOC-2258) should be "Need way to pin ZFS versions on RPM distributions"
- :heavy_check_mark: [FLOC-2183](https://clusterhq.atlassian.net/browse/FLOC-2183) is OK
- :heavy_check_mark: [FLOC-2182](https://clusterhq.atlassian.net/browse/FLOC-2182) is OK
- :heavy_check_mark: [FLOC-2179](https://clusterhq.atlassian.net/browse/FLOC-2179) is OK
- :negative_squared_cross_mark: [FLOC-2187](https://clusterhq.atlassian.net/browse/FLOC-2187) should be "flocker/functional/aws/centos-7/storage-driver builder should be part of expected passing set of builders for GitHub PRs"
- :negative_squared_cross_mark: [FLOC-2186](https://clusterhq.atlassian.net/browse/FLOC-2186) should be "flocker/acceptance/rackspace/ubuntu-14.04/rackspace builder should be part of expected passing set of builders for GitHub PRs"
- :negative_squared_cross_mark: [FLOC-2185](https://clusterhq.atlassian.net/browse/FLOC-2185) should be "flocker/acceptance/rackspace/ubuntu-14.04/loopback builder should be part of expected passing set of builders for GitHub PRs"
- :negative_squared_cross_mark: [FLOC-2184](https://clusterhq.atlassian.net/browse/FLOC-2184) should be "flocker/acceptance/rackspace/centos-7/rackspace builder should be part of expected passing set of builders for GitHub PRs"

Note that all of these issues are Done, either because they are done, or because they are marked "won't do".

**Comment by jml** [comment]
Was a stupid scope issue. I've fixed the code and made it faster.

I went on a long tangent writing nice and thorough tests for a piece of code that I then deleted. See them here: https://gist.github.com/jml/5163263751abad0a1853

**Comment by exarkun** [comment]
This was really confusing for a few minutes:

```
$ python blockers.py FLOC-3165
FLOC-2008: Release 1.0 blockers - Done
├── FLOC-2258: Need way to pin ZFS versions on RPM distributions - Done
├── FLOC-2183: flocker/acceptance/ubuntu-14.04/aws builder should be part of expected passing set of builders for GitHub PRs - Done
├── FLOC-2182: flocker/acceptance/rackspace/centos-7/loopback builder should be part of expected passing set of builders for GitHub PRs - Done
├── FLOC-2179: Builder ``flocker/acceptance/aws/centos-7/aws`` should be part of known passing builders - Done (madhuri.yechuri)
├── FLOC-2187: flocker/functional/aws/centos-7/storage-driver builder should be part of expected passing set of builders for GitHub PRs - Done
├── FLOC-2186: flocker/acceptance/rackspace/ubuntu-14.04/rackspace builder should be part of expected passing set of builders for GitHub PRs - Done
├── FLOC-2185: flocker/acceptance/rackspace/ubuntu-14.04/loopback builder should be part of expected passing set of builders for GitHub PRs - Done
└── FLOC-2184: flocker/acceptance/rackspace/centos-7/rackspace builder should be part of expected passing set of builders for GitHub PRs - Done
```

**Pull request merged**
